
#ifndef CAApis_h
#define CAApis_h

FOUNDATION_EXTERN NSString * const CAAPI_BASE_URL;
FOUNDATION_EXTERN NSString * const WEBSOCKET_URL;
FOUNDATION_EXTERN NSString * const MATCHER_BASE_URL;

FOUNDATION_EXTERN NSString * const CAAPI_HOMEAPI;
FOUNDATION_EXTERN NSString * const CAAPI_CHECK_FOR_UPDATES;

FOUNDATION_EXTERN NSString * const CAAPI_CURRENCY_DETAILS;
FOUNDATION_EXTERN NSString * const CAAPI_CURRENCY_DEPOSIT_ADDRESS;
FOUNDATION_EXTERN NSString * const CAAPI_CURRENCY_SHOW_INTERNAL_TRANSFER_PAGE;
FOUNDATION_EXTERN NSString * const CAAPI_CURRENCY_INTERNAL_TRANSFER;
FOUNDATION_EXTERN NSString * const CAAPI_CURRENCY_GRNERATE_DEPOSIT_ADDRESS;
FOUNDATION_EXTERN NSString * const CAAPI_CURRENCY_SHOW_WITHDRAW_PAGE;

FOUNDATION_EXTERN NSString * const CAAPI_CURRENCY_WITHDRAW;

FOUNDATION_EXTERN NSString * const CAAPI_COMMON_CONUNTRY_CODES;

FOUNDATION_EXTERN NSString * const CAAPI_OTC_MY_ADVERTISEMENTS;
FOUNDATION_EXTERN NSString * const CAAPI_OTC_MY_ORDERS;
FOUNDATION_EXTERN NSString * const CAAPI_OTC_LANDING;
FOUNDATION_EXTERN NSString * const CAAPI_OTC_GET_ADVERTISEMENTS;
FOUNDATION_EXTERN NSString * const CAAPI_OTC_IS_ADVERTISEMENT_CANCELLED;
FOUNDATION_EXTERN NSString * const CAAPI_OTC_SHOW_TRADING;
FOUNDATION_EXTERN NSString * const CAAPI_OTC_EDIT_ADVERTISEMENT;
FOUNDATION_EXTERN NSString * const CAAPI_OTC_CREATE_TRADING;
FOUNDATION_EXTERN NSString * const CAAPI_OTC_CANCLE_TRADING;
FOUNDATION_EXTERN NSString * const CAAPI_OTC_MARK_BUYER_HAS_PAID;
FOUNDATION_EXTERN NSString * const CAAPI_OTC_MARK_TRADING_OVERTIME;
FOUNDATION_EXTERN NSString * const CAAPI_OTC_SELLER_HAS_RELEASED;
FOUNDATION_EXTERN NSString * const CAAPI_OTC_CREATE_ADVERTISEMENT;
FOUNDATION_EXTERN NSString * const CAAPI_OTC_UPDATE_ADVERTISEMENT;
FOUNDATION_EXTERN NSString * const CAAPI_OTC_UPDATE_ADVERTISEMENT_IS_CANCLLED_STATUS;
FOUNDATION_EXTERN NSString * const CAAPI_OTC_EDIT_NICK_NAME;
FOUNDATION_EXTERN NSString * const CAAPI_OTC_UPDATE_NICK_NAME;
FOUNDATION_EXTERN NSString * const CAAPI_OTC_CREATE_DISPUTE;
FOUNDATION_EXTERN NSString * const CAAPI_OTC_MESSAGES;

FOUNDATION_EXTERN NSString * const CAAPI_MEMBERS_UPDATE_PASSWORD;
FOUNDATION_EXTERN NSString * const CAAPI_MEMBERS_SIGN_IN;
FOUNDATION_EXTERN NSString * const CAAPI_MEMBERS_SIGN_OUT;
FOUNDATION_EXTERN NSString * const CAAPI_MEMBERS_SIGN_UP;
FOUNDATION_EXTERN NSString * const CAAPI_MEMBERS_SEND_EMAIL_TOKEN_FOR_SIGN_UP;
FOUNDATION_EXTERN NSString * const CAAPI_MEMBERS_SEND_SMS_TOKEN_FOR_SIGN_UP;
FOUNDATION_EXTERN NSString * const CAAPI_MEMBERS_SEND_SMS_TOKEN_TO_MEMBER;
FOUNDATION_EXTERN NSString * const CAAPI_MEMBERS_FORGOT_PASSWORD_SEND_SMS_CODE;
FOUNDATION_EXTERN NSString * const CAAPI_MEMBERS_FORGOT_PASSWORD_SEND_EMAIL_CODE;
FOUNDATION_EXTERN NSString * const CAAPI_MEMBERS_GORGOT_PASWORD;

FOUNDATION_EXTERN NSString * const CAAPI_MINE_GET_BIND_MOBILE;
FOUNDATION_EXTERN NSString * const CAAPI_MINE_BIND_MOBILE;
FOUNDATION_EXTERN NSString * const CAAPI_MINE_EDIT_BIND_EMAIL;
FOUNDATION_EXTERN NSString * const CAAPI_MINE_BIDN_EMAIL;
FOUNDATION_EXTERN NSString * const CAAPI_MINE_UNBIDN_EMAIL;
FOUNDATION_EXTERN NSString * const CAAPI_MINE_INVITATION_CODE;
FOUNDATION_EXTERN NSString * const CAAPI_MINE_ASSETS;
FOUNDATION_EXTERN NSString * const CAAPI_MINE_ASSETS_RECORDS;
FOUNDATION_EXTERN NSString * const CAAPI_MINE_FRIENDS;
FOUNDATION_EXTERN NSString * const CAAPI_MINE_SEND_SMS_VALIDATION_CODE;
FOUNDATION_EXTERN NSString * const CAAPI_MINE_UPDATE_ASSET_PASSWORD;
FOUNDATION_EXTERN NSString * const CAAPI_MINE_SEND_BIND_EMAIL_CODE;
FOUNDATION_EXTERN NSString * const CAAPI_MINE_UPLOAD_ID_CARD_FILES;
FOUNDATION_EXTERN NSString * const CAAPI_MINE_PERSONAL_CENTER;
FOUNDATION_EXTERN NSString * const CAAPI_MINE_SHOW_PAYMENT_METHODS_PAGE;
FOUNDATION_EXTERN NSString * const CAAPI_MINE_UPDATE_PAYMENT_METHODS;
FOUNDATION_EXTERN NSString * const CAAPI_MINE_UPDATE_PAYMENT_ACTIVATED_STATUS;
FOUNDATION_EXTERN NSString * const CAAPI_MINE_NEW_PAYMENT_METHOD;
FOUNDATION_EXTERN NSString * const CAAPI_MINE_ENTER_ASSET_PASSWORD;
FOUNDATION_EXTERN NSString * const CAAPI_MINE_UPDATE_ASSET_PASSWORD_SEND_EMAIL_CODE;
FOUNDATION_EXTERN NSString * const CAAPI_MINE_UPDATE_ASSET_PASSWORD_SEND_MOBILE_CODE;
FOUNDATION_EXTERN NSString * const CAAPI_MINE_ASSETS_RECORDS_DETAIL;
FOUNDATION_EXTERN NSString * const CAAPI_MINE_FEEDBACK;
FOUNDATION_EXTERN NSString * const CAAPI_MINE_UPLOAD_ID_CARD_INFORMATION;
FOUNDATION_EXTERN NSString * const CAAPI_MINE_AFTER_SCAN_FACE;

FOUNDATION_EXTERN NSString * const CAAPI_CRYPTO_TO_CRYPTO_MARKET_SCALE;
FOUNDATION_EXTERN NSString * const CAAPI_CRYPTO_TO_CRYPTO_CREATE_ORDER;
FOUNDATION_EXTERN NSString * const CAAPI_CRYPTO_TO_CRYPTO_IS_ADD_TO_FAVORATES;
FOUNDATION_EXTERN NSString * const CAAPI_CRYPTO_TO_CRYPTO_ADD_TO_FAVAORATES;
FOUNDATION_EXTERN NSString * const CAAPI_CRYPTO_TO_CRYPTO_REMOVE_FROM_FAVAORATES;
FOUNDATION_EXTERN NSString * const CAAPI_CRYPTO_TO_CRYPTO_CURRENT_ORDERS;
FOUNDATION_EXTERN NSString * const CAAPI_CRYPTO_TO_CRYPTO_ORDERS;
FOUNDATION_EXTERN NSString * const CAAPI_CRYPTO_TO_CRYPTO_MY_ORDERS;
FOUNDATION_EXTERN NSString * const CAAPI_CRYPTO_TO_CRYPTO_CANCEL_ORDERS;
FOUNDATION_EXTERN NSString * const CAAPI_CRYPTO_TO_CRYPTO_CANCEL_ALL_ORDERS;
FOUNDATION_EXTERN NSString * const CAAPI_CRYPTO_TO_CRYPTO_TRADE_DEATAIL;
FOUNDATION_EXTERN NSString * const CAAPI_CRYPTO_TO_CRYPTO_GET_MARKETS;
FOUNDATION_EXTERN NSString * const CAAPI_CRYPTO_TO_CRYPTO_SHOW_ALL_FAVOURITE_MARKETS_DETAILS;

#endif /* CAApis_h */
